//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int billID { get; set; }
        public System.DateTime billDate { get; set; }
        public string tenantID { get; set; }
        public decimal rentalCharge { get; set; }
        public decimal income { get; set; }
        public decimal totalCharge { get; set; }
    
        public virtual tenant tenant { get; set; }
    }
}
