//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.buyorders = new HashSet<buyorder>();
            this.showcases = new HashSet<showcase>();
        }
    
        public string branchID { get; set; }
        public string branchName { get; set; }
        public string telephone { get; set; }
        public string billingAddress { get; set; }
        public string emailAddress { get; set; }
    
        public virtual ICollection<buyorder> buyorders { get; set; }
        public virtual ICollection<showcase> showcases { get; set; }
    }
}
