//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyorder
    {
        public buyorder()
        {
            this.orderitems = new HashSet<orderitem>();
        }
    
        public long orderID { get; set; }
        public string customerID { get; set; }
        public decimal totalAmount { get; set; }
        public System.DateTime orderDateTime { get; set; }
        public string pickupPlace { get; set; }
        public string status { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<orderitem> orderitems { get; set; }
    }
}
