//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public long orderID { get; set; }
        public string productID { get; set; }
        public int quantity { get; set; }
        public decimal sellingPrice { get; set; }
        public int totalPrice { get; set; }
    
        public virtual buyorder buyorder { get; set; }
        public virtual product product { get; set; }
    }
}
