//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public region()
        {
            this.districts = new HashSet<district>();
        }
    
        public int regionID { get; set; }
        public string regionName { get; set; }
    
        public virtual ICollection<district> districts { get; set; }
    }
}
