//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class showcase
    {
        public showcase()
        {
            this.products = new HashSet<product>();
            this.reservations = new HashSet<reservation>();
            this.rentrecords = new HashSet<rentrecord>();
        }
    
        public long showcaseID { get; set; }
        public string tenantID { get; set; }
        public string branchID { get; set; }
        public string monthlyRent { get; set; }
        public string status { get; set; }
        public string End_Day { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual tenant tenant { get; set; }
        public virtual ICollection<rentrecord> rentrecords { get; set; }
    }
}
