//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4915M_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.salesrecords = new HashSet<salesrecord>();
        }
    
        public string staffID { get; set; }
        public string staffName { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public string telephone { get; set; }
        public string hiringType { get; set; }
        public System.DateTime hireDate { get; set; }
        public string position { get; set; }
        public Nullable<decimal> commissionRate { get; set; }
        public byte[] avatar { get; set; }
    
        public virtual ICollection<salesrecord> salesrecords { get; set; }
    }
}
